local Res = {}

Res.common_topTipBg           = "image/common/topTipBg.png"
Res.common_halfTrans          = "image/common/halfTrans60.png"
Res.common_progressBg2        = "image/common/progressBg2.png"
Res.common_progress2          = "image/common/progress2.png"
Res.common_headMask           = "image/common/headMask.png"
Res.common_defaultWoman       = "image/common/defaultWoman.png"
Res.common_defaultMan         = "image/common/defaultMan.png"
Res.common_btnYellowM         = "image/common/btnYellowM.png"
Res.common_btnGreenB          = "image/common/btnGreenB.png"
Res.common_btnYellowB         = "image/common/btnYellowB.png"
Res.common_btnBlueS           = "image/common/btnBlueS.png"
Res.common_coinIcon           = "image/common/coinIcon.png"
Res.common_headFrame          = "image/common/circle.png"
Res.common_redCircle          = "image/common/redCircle.png"
Res.common_searchIcon         = "image/common/searchIcon.png"
Res.common_chatIcon           = "image/common/chatIcon.png"
Res.common_friendIcon         = "image/common/friendIcon.png"
Res.common_friendAddIcon      = "image/common/friendAddIcon.png"
Res.common_gender0            = "image/common/gender0.png"
Res.common_gender1            = "image/common/gender1.png"
Res.common_baseInfoIcon       = "image/common/baseInfoIcon.png"
Res.common_editIcon           = "image/common/editIcon.png"
Res.common_cameraIcon         = "image/common/cameraIcon.png"
Res.common_redDot             = "image/common/redDot.png"
Res.common_back               = "image/common/back.png"
Res.common_progress_img       = "image/common/progress_img.png"

Res.commonroom_back           = "image/commonroom/back.png"


Res.errorBg                   = "bg2.jpg"
Res.loginBg                   = "katoBig.jpg"
Res.hallBg                    = "katoBig2.jpg"
Res.kato                      = "kato.jpg"
Res.black                     = "image/common/black.png"
Res.loadingIcon               = "image/common/loadingIcon.png"
Res.loadingBg                 = "image/common/loadingBg.png"
Res.blank                     = "image/common/blank.png"

-- login
Res.login_loginBg             = "image/login/loginBg.jpg"

-- hall
Res.hall_hallBg               = "image/hall/hallBg.jpg"
Res.hall_userInfoBg           = "image/hall/hallUserInfoBg.png"

-- moneyTree
Res.moneytree_bg              = "image/activity/moneytree/bg.jpg"
Res.moenytree_iconGold        = "platform/image/activity/moneytree/moneyTreeIconGold.png"
Res.moenytree_iconChip        = "platform/image/activity/moneytree/moneyTreeIconChip.png"
Res.moenytree_whiteBg         = "image/activity/moneytree/whiteBg.png"
Res.moenytree_goldCoin        = "image/activity/moneytree/goldCoin.png"
Res.moenytree_chipCoin        = "image/activity/moneytree/chipCoin.png"
Res.moenytree_samllGoldIcon   = "image/activity/moneytree/samllGoldIcon.png"
Res.moenytree_samllChipIcon   = "image/activity/moneytree/samllChipIcon.png"
Res.moenytree_myGoldBg        = "image/activity/moneytree/myGoldBg.png"
Res.moenytree_rightBoardBg    = "image/activity/moneytree/rightBoardBg.png"
Res.moenytree_bubble          = "image/activity/moneytree/bubble.png"
Res.moenytree_goldCoinLimitBg = "image/activity/moneytree/goldCoinLimitBg.png"
Res.moenytree_descBgBoarder   = "image/activity/moneytree/descBgBoarder.png"
Res.moenytree_descBgLinker    = "image/activity/moneytree/descBgLinker.png"
Res.moenytree_rayParticle     = "image/activity/moneytree/rayParticle.plist"
Res.moenytree_starParticle    = "image/activity/moneytree/starParticle.plist"
Res.moenytree_samllGoldIcon   = "image/activity/moneytree/samllGoldIcon.png"
Res.moenytree_samllChipIcon   = "image/activity/moneytree/samllChipIcon.png"
Res.moenytree_bubble          = "image/activity/moneytree/bubble.png"
Res.moenytree_goldCoin        = "image/activity/moneytree/goldCoin.png"
Res.moenytree_chipCoin        = "image/activity/moneytree/chipCoin.png"
Res.moneytree_backIcon        = "image/activity/moneytree/backIcon.png"
Res.moneytree_can             = "image/activity/moneytree/can.png"
Res.moneytree_canButton       = "image/activity/moneytree/canButton.png"
Res.moneytree_chipIconMid     = "image/activity/moneytree/chipIconMid.png"
Res.moneytree_goldIconMid     = "image/activity/moneytree/goldIconMid.png"
Res.moneytree_chipEntrance    = "platform/image/activity/moneytree/chipEntrance.png"
Res.moneytree_friendDynamics  = "platform/image/activity/moneytree/friendDynamics.png"
Res.moneytree_noticeBar       = "image/activity/moneytree/noticeBar.png"
Res.moneytree_questionIcon    = "image/activity/moneytree/questionIcon.png"
Res.moneytree_shareIcon       = "image/activity/moneytree/shareIcon.png"
Res.moneytree_tipsFrame       = "image/activity/moneytree/tipsFrame.png"
Res.moneytree_tipsFrameArrow  = "image/activity/moneytree/tipsFrameArrow.png"
Res.moneytree_titleBar        = "platform/image/activity/moneytree/titleBar.png"
Res.moneytree_treeFormat      = "image/activity/moneytree/tree%s.png"
Res.moneytree_VS              = "image/activity/moneytree/VS.png"
Res.moneytree_waterDrop       = "image/activity/moneytree/waterDrop.png"
Res.moneytree_waterLbl        = "platform/image/activity/moneytree/waterLbl.png"
Res.moneytree_whiteBar        = "image/activity/moneytree/whiteBar.png"
Res.moneytree_whiteDot        = "image/activity/moneytree/whiteDot.png"
Res.moneytree_stealBg         = "image/activity/moneytree/stealBg.png"
Res.moneytree_stealIcon       = "image/activity/moneytree/stealIcon.png"
Res.moneytree_myTreeIcon      = "image/activity/moneytree/myTreeIcon.png"
Res.moneytree_myTreeLbl       = "platform/image/activity/moneytree/myTreeLbl.png"
Res.moneytree_treeLevelBg     = "image/activity/moneytree/treeLevelBg.png"
Res.moneytree_redDot          = "image/activity/moneytree/redDot.png"
Res.moneytree_hand            = "image/activity/moneytree/hand.png"
Res.moneytree_myInfoBg        = "image/activity/moneytree/right1.png"
Res.moneytree_myDynamicsBg    = "image/activity/moneytree/right2.png"
Res.moneytree_vsInfoBg        = "image/activity/moneytree/right3.png"
Res.moneytree_imageFrameR     = "image/activity/moneytree/imageFrame1.png"
Res.moneytree_imageFrameL     = "image/activity/moneytree/imageFrame2.png"
Res.moneytree_chipBg          = "image/activity/moneytree/chipBg.png"
Res.moneytree_vsInfoBg2       = "image/activity/moneytree/vsInfoBg2.png"
Res.moneytree_rankBg          = "image/activity/moneytree/rankBg.png"
Res.moneytree_rankItemBg      = "image/activity/moneytree/rankItemBg.png"
Res.moneytree_rankItemSelfBg  = "image/activity/moneytree/rankItemSelfBg.png"
Res.moneytree_rankTreeIcon    = "image/activity/moneytree/rankTreeIcon.png"
Res.moneytree_friendRank      = "platform/image/activity/moneytree/friendRank.png"
Res.moneytree_coinSrcRecordBg = "image/activity/moneytree/coinSrcRecordBg.png"
Res.moneytree_guideTipArrow   = "image/activity/moneytree/guideTipArrow.png"
Res.moneytree_guideTipBg      = "image/activity/moneytree/guideTipBg.png"
Res.moneytree_selected        = "image/activity/moneytree/selected.png"

Res.moneytreeinvite_bg        = "image/activity/moneytree/inviteBg.png"
Res.moneytreeinvite_chipBar   = "image/activity/moneytree/inviteChipBar.png"
Res.moneytreeinvite_codeBg    = "image/activity/moneytree/inviteCodeBg.png"
Res.moneytreeinvite_infoChip  = "platform/image/activity/moneytree/inviteInfoChip.png"
Res.moneytreeinvite_infoGold  = "platform/image/activity/moneytree/inviteInfoGold.png"
Res.moneytreeinvite_close     = "image/activity/moneytree/inviteClose.png"

return Res
